### PR TITLE
add updated package

### PR DESCRIPTION
**Pull request by martinlardi**

### CODE REVIEW

**Comment by dpastoor** [comment]
I don't think the latest python version is compatible is it? We hit this issue before, did you confirm that python version presents in the marketplace UI in code server? @xuf12 remember this issue

**Comment by xuf12** [comment]
yes we are going to fix that ([ref](https://a2-ai.atlassian.net/browse/SER-1?focusedCommentId=10153))

**Comment by martinlardi** [comment]
image
Jupyter extension didn't work

**Comment by martinlardi** [comment]
image
Delete Jupyter extension because when you install python extension, it automatically install jupyter extension as well

**Comment by martinlardi** [comment]
> image Delete Jupyter extension because when you install python extension, it automatically install jupyter extension as well

Update quarto, lua and latex extension to latest version

**Comment by martinlardi** [comment]
Write a documentation in my space (confluence). Will move it to propriate place later 
Link : https://a2-ai.atlassian.net/wiki/spaces/~712020ed1aa7f5ed4f45d6989f1c40fbce9cb3/pages/105611374/VS+Code+Extension

**Review by xuf12 — APPROVED** [review]
LGTM.

**Pull request merged**
